language: c
sudo: false

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake

env:
  global:
    # For LuaJIT 2.1, see https://github.com/LuaJIT/LuaJIT/commit/8961a92dd1607108760694af3486b4434602f8be
    - MACOSX_DEPLOYMENT_TARGET=10.12
    - WITH_LUA_ENGINE=Lua
    - BUILD_SHARED_LIBS=On
    - BUILD_MODULE=Off
os:
  - osx

script:
  - make
